---
image: gitlab.cosmian.com:5000/core/ci-rust:latest

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo/
  SCCACHE_DIR: ${CI_PROJECT_DIR}/.cache/sccache
  COSMIAN_SERVER_URL: http://localhost:9998
  KMS_PUBLIC_PATH: /tmp
  KMS_PRIVATE_PATH: /tmp
  KMS_SHARED_PATH: /tmp

services:
  - name: gitlab.cosmian.com:5000/core/kms:${KMS_VERSION}_ci
    alias: kms_ci
  - redis:latest

stages:
  - prebuild
  - build
  - test
  - pack
  - publish

rustfmt:
  stage: prebuild
  cache: {}
  script:
    - cargo +stable format

doc:
  stage: prebuild
  cache: {}
  script:
    - cargo doc --all-features

clippy:
  stage: prebuild
  cache: {}
  script:
    # all features activated
    - cargo clippy --all-targets -- -D warnings
    # no feature activated
    - cargo clippy-all

# Security check
cargo_security_check:
  stage: prebuild
  cache: {}
  script:
    - cargo outdated -wR
    - cargo audit --deny warnings
  allow_failure: true

is_publishable:
  stage: prebuild
  cache: {}
  script:
    - rm -rf /tmp/${CI_PROJECT_NAME}
    - cp -rf . /tmp/${CI_PROJECT_NAME}
    - cd /tmp/${CI_PROJECT_NAME}
    - cargo publish --dry-run
    - rm -rf /tmp/${CI_PROJECT_NAME}
  allow_failure: true

is_semver_broken:
  stage: prebuild
  cache: {}
  script:
    - cargo semver-checks check-release

#
# Build base
#
.base_compile: &base_compile
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - $CARGO_HOME
      - $SCCACHE_DIR
  before_script:
    - sccache -s

build_x86_64:
  <<: *base_compile
  script:
    - cargo build --release --features ffi --target x86_64-unknown-linux-gnu
    - cargo test --release --all-features --target x86_64-unknown-linux-gnu
    - cbindgen . -c cbindgen.toml | grep -v \#include | uniq >target/${CI_PROJECT_NAME}.h

build_x86_64_centos7:
  <<: *base_compile
  image: gitlab.cosmian.com:5000/core/ci-rust-glibc-2.17
  script:
    - cargo build --release --features ffi --target x86_64-unknown-linux-gnu
    - cargo test --release --features ffi --target x86_64-unknown-linux-gnu
    - cbindgen . -c cbindgen.toml | grep -v \#include | uniq >target/${CI_PROJECT_NAME}.h
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/*.so
      - target/*.h
    expire_in: 3 mos

build_wasm:
  <<: *base_compile
  image: gitlab.cosmian.com:5000/core/ci-npm:latest
  script:
    - wasm-pack build -d pkg/bundler --target web --release --features wasm_bindgen
    - wasm-pack test --node --features wasm_bindgen --lib
    - wasm-pack build -d pkg/nodejs --target nodejs --release --features wasm_bindgen
  artifacts:
    paths:
      - pkg
    expire_in: 3 mos

build_windows:
  <<: *base_compile
  script:
    - cargo build --release --features ffi --target x86_64-pc-windows-gnu
    - cbindgen . -c cbindgen.toml | grep -v \#include | uniq >target/${CI_PROJECT_NAME}.h
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/*.dll
      - target/*.h
    expire_in: 3 mos

build_osx:
  stage: build
  tags:
    - mac
  before_script:
    - rustup target add aarch64-apple-ios x86_64-apple-darwin x86_64-apple-ios
  script:
    - cargo build --release --features ffi --target x86_64-apple-darwin
    - cargo lipo --release --features ffi
  artifacts:
    paths:
      - target/x86_64-apple-darwin/release/*.dylib
      - target/universal/release/*.a
    expire_in: 3 mos

build_android:
  <<: *base_compile
  image: gitlab.cosmian.com:5000/core/ci-rust-android:latest
  script:
    - cargo ndk -t x86 -t x86_64 -t armeabi-v7a -t arm64-v8a -o jniLibs build --release --features ffi --lib
  artifacts:
    paths:
      - jniLibs
    expire_in: 3 mos

benchmarks:
  stage: build
  before_script:
    - apt update && apt install -y gnuplot
  script:
    - cargo bench --features full_bench,hybrid
  when: manual

build_python_linux:
  stage: build
  image:
    name: ghcr.io/pyo3/maturin
    # remove the image custom entrypoint because it is not supported by gitlab runners
    entrypoint: ['']
  script:
    # Build for glibc 2.17
    - maturin build --compatibility manylinux_2_17 --release --features python
  artifacts:
    paths:
      - target/wheels/*manylinux*.whl
    expire_in: 3 mos

build_python_windows:
  <<: *base_compile
  script:
    - pip install -r src/interfaces/pyo3/tests/requirements.txt
    - maturin build --release --features python --target x86_64-pc-windows-gnu
  artifacts:
    paths:
      - target/wheels/*win_amd64.whl
    expire_in: 3 mos

build_python_osx:
  stage: build
  tags:
    - mac
  before_script:
    - rustup target add x86_64-apple-darwin
  script:
    - pip3 install -r src/interfaces/pyo3/tests/requirements.txt
    - maturin build --release --features python --target x86_64-apple-darwin
  artifacts:
    paths:
      - target/wheels/*macosx*.whl
    expire_in: 3 mos

test_cloudproof_java:
  image: openjdk:8
  stage: test
  before_script:
    - apt update && apt install -y maven
  script:
    - git clone https://github.com/Cosmian/cloudproof_java.git
    - cp target/x86_64-unknown-linux-gnu/release/libcosmian_${CI_PROJECT_NAME}.so cloudproof_java/src/main/resources/linux-x86-64/
    - cd cloudproof_java
    - mvn package
  allow_failure: true

test_python:
  stage: test
  script:
    - pip install --force-reinstall target/wheels/*manylinux*.whl
    - python3 src/interfaces/pyo3/tests/test_cover_crypt.py

test_cloudproof_js:
  image: node:18
  stage: test
  script:
    - git clone https://github.com/Cosmian/cloudproof_js.git
    - mkdir -p cloudproof_js/tests/wasm_lib/cosmian_${CI_PROJECT_NAME}
    - cp -r pkg/nodejs/* cloudproof_js/tests/wasm_lib/cosmian_${CI_PROJECT_NAME}/
    - cd cloudproof_js
    - npm install jest
    - npm test
  allow_failure: true

test_cloudproof_flutter:
  tags:
    - mac
  stage: test
  script:
    - git clone https://github.com/Cosmian/cloudproof_flutter.git
    - cp target/x86_64-apple-darwin/release/libcosmian_${CI_PROJECT_NAME}.dylib cloudproof_flutter/resources/
    - cd cloudproof_flutter
    - flutter pub get
    - flutter test
  allow_failure: true

pack_all_artifacts:
  stage: pack
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  before_script:
    - apt update && apt install -y zip
  script:
    - zip -r ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}-bin.zip pkg target jniLibs
  artifacts:
    name: cosmian_${CI_PROJECT_NAME}_${CI_COMMIT_TAG}
    paths:
      - ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}-bin.zip
    expire_in: 3 mos

npm_publish:
  image: gitlab.cosmian.com:5000/core/ci-npm:latest
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" > ~/.npmrc
    - wasm-pack build --target web --release --features wasm_bindgen
    - wasm-pack pack
    - wasm-pack publish

cargo_publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - echo "[registry]" > ~/.cargo/credentials
    - echo "token = \"$CRATES_IO\"" >> ~/.cargo/credentials
    - rm -rf /tmp/${CI_PROJECT_NAME}
    - cp -rf . /tmp/${CI_PROJECT_NAME}
    - cd /tmp/${CI_PROJECT_NAME}
    - rm -rf ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}-bin.zip cosmian_${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip jniLibs target
    - cargo publish --token $CRATES_IO
    - rm -rf /tmp/${CI_PROJECT_NAME}

python_publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - pip install twine
    - twine upload -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}" target/wheels/cover_crypt-${CI_COMMIT_TAG}*.whl

# Finally, run benchmarks at once
benchmarks:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  before_script:
    - apt update && apt install -y gnuplot
  script:
    - cargo bench --all-features
