---
image: gitlab.cosmian.com:5000/core/ci-rust:latest

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo/
  SCCACHE_DIR: ${CI_PROJECT_DIR}/.cache/sccache
  COSMIAN_SERVER_URL: http://localhost:9998
  KMS_PUBLIC_PATH: /tmp
  KMS_PRIVATE_PATH: /tmp
  KMS_SHARED_PATH: /tmp

services:
  - name: gitlab.cosmian.com:5000/core/kms:${KMS_VERSION}_ci
    alias: kms_ci
  - redis:latest

stages:
  - prebuild
  - build
  - test
  - cross_test
  - pack
  - publish

static_analysis:
  stage: prebuild
  cache: {}
  script:
    - cargo format
    - cargo doc --all-features
    # no feature activated
    - cargo clippy --all-targets -- -D warnings
    # all features activated
    - cargo clippy-all
    # Check semver
    - cargo semver-checks check-release

# Security check
security_check:
  stage: prebuild
  cache: {}
  script:
    # Check is crate is publishable
    - rm -rf /tmp/${CI_PROJECT_NAME}
    - cp -rf . /tmp/${CI_PROJECT_NAME}
    - pushd /tmp/${CI_PROJECT_NAME}
    - cargo publish --dry-run
    - rm -rf /tmp/${CI_PROJECT_NAME}
    - popd
    # Check deprecated dependencies
    - cargo outdated -wR
    - cargo audit --deny warnings
  allow_failure: true

#
# Build base
#
.cache:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - $CARGO_HOME
      - $SCCACHE_DIR
  before_script:
    - sccache -s

.base_compile:
  extends: .cache

.base_test:
  stage: test

build_x86_64_centos7:
  extends: .cache
  image: gitlab.cosmian.com:5000/core/ci-rust-glibc-2.17
  script:
    - cargo build --release --features ffi --target x86_64-unknown-linux-gnu
    - cbindgen . -c cbindgen.toml | grep -v \#include | uniq >target/${CI_PROJECT_NAME}.h
    - cargo test --release --all-features --target x86_64-unknown-linux-gnu
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/*.so
      - target/*.h
      - target/non_regression_vector.json
    expire_in: 3 mos

test_cloudproof_java:
  extends: .base_test
  image: openjdk:8
  before_script:
    - apt update && apt install -y maven
  script:
    - git clone --branch main https://github.com/Cosmian/cloudproof_java.git
    - cp target/x86_64-unknown-linux-gnu/release/libcosmian_${CI_PROJECT_NAME}.so cloudproof_java/src/main/resources/linux-x86-64/
    - cd cloudproof_java
    - mvn package
  artifacts:
    paths:
      - cloudproof_java/target/test-classes/java_non_regression_vector.json
    expire_in: 3 mos

  allow_failure: true

build_wasm:
  extends: .base_compile
  image: gitlab.cosmian.com:5000/core/ci-npm:latest
  script:
    - wasm-pack build -d pkg/web --target web --release --features wasm_bindgen
    - wasm-pack test --node --features wasm_bindgen --lib
  artifacts:
    paths:
      - pkg
    expire_in: 3 mos

test_cloudproof_js:
  extends: .base_test
  image: node:18
  script:
    - git clone --branch main https://github.com/Cosmian/cloudproof_js.git
    - mkdir -p cloudproof_js/src/pkg/${CI_PROJECT_NAME}
    - cd cloudproof_js
    # Replace pkg with fresh build
    - cp -r ../pkg/web/* cloudproof_js/src/pkg/${CI_PROJECT_NAME}/
    - npm install
    - npm test
  artifacts:
    paths:
      - cloudproof_js/node_modules/non_regression_test_vector.json
    expire_in: 3 mos
  allow_failure: true

build_osx:
  stage: build
  tags:
    - mac
  before_script:
    - rustup target add aarch64-apple-ios x86_64-apple-darwin x86_64-apple-ios
  script:
    - cargo build --release --features ffi --target x86_64-apple-darwin
    - cargo lipo --release --features ffi
    # python build
    - pip3 install -r python/requirements.txt
    # custom `target_dir` to avoid overwriting flutter `dylib`
    # the wheel python package is still saved in `./target`
    - maturin build --release --features python --target x86_64-apple-darwin --target-dir target_python
  artifacts:
    paths:
      - target/x86_64-apple-darwin/release/*.dylib
      - target/universal/release/*.a
      - target/wheels/*macosx*.whl
    expire_in: 3 mos

test_cloudproof_flutter:
  tags:
    - mac
  script:
    - git clone --branch main https://github.com/Cosmian/cloudproof_flutter.git
    - cp target/x86_64-apple-darwin/release/libcosmian_${CI_PROJECT_NAME}.dylib cloudproof_flutter/resources/
    - cd cloudproof_flutter
    - flutter pub get
    - flutter test
  artifacts:
    paths:
      - cloudproof_flutter/build/non_regression_test_vector.json
    expire_in: 3 mos
  allow_failure: true

build_python_manylinux:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  image:
    name: ghcr.io/pyo3/maturin:v0.14.1
    # remove the image custom entrypoint because it is not supported by gitlab runners
    entrypoint: ['']
  script:
    # Build for glibc 2.17
    - maturin build --compatibility manylinux_2_17 --release --features python --target-dir target_python
    - pip install target/wheels/*manylinux*.whl
    - pip install -r python/requirements.txt
    - mypy python/scripts/test_${CI_PROJECT_NAME}.py
    - python3 python/scripts/test_${CI_PROJECT_NAME}.py
  artifacts:
    paths:
      - target/wheels/*manylinux*.whl
    expire_in: 3 mos

cross_compatibility_checks:
  stage: cross_test
  image: node:18
  before_script:
    - apt update && apt install -y software-properties-common sqlite3 libsqlite3-dev wget xz-utils git
    - wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
    - add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
    - apt update && apt install -y adoptopenjdk-8-hotspot
    - apt install -y maven
    - java -version
    - mvn --version
    - wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.3.4-stable.tar.xz -O /tmp/flutter_linux_3.3.4-stable.tar.xz
    - tar xf /tmp/flutter_linux_3.3.4-stable.tar.xz --directory /tmp
    - git config --global --add safe.directory /tmp/flutter
    - export PATH="$PATH:/tmp/flutter/bin"
    - flutter doctor
  script:
    #
    # Java tests
    #
    - git clone --branch main https://github.com/Cosmian/cloudproof_java.git
    - cp target/x86_64-unknown-linux-gnu/release/libcosmian_${CI_PROJECT_NAME}.so cloudproof_java/src/main/resources/linux-x86-64/
    - cp target/non_regression_vector.json cloudproof_java/src/test/resources/cover_crypt/rust_non_regression_vector.json
    - cp cloudproof_java/target/test-classes/java_non_regression_vector.json cloudproof_java/src/test/resources/cover_crypt/other_java_java_non_regression_vector.json
    - cp cloudproof_js/node_modules/non_regression_test_vector.json cloudproof_java/src/test/resources/cover_crypt/
    - cp cloudproof_flutter/build/non_regression_test_vector.json cloudproof_java/src/test/resources/cover_crypt/
    - cd cloudproof_java
    - mvn package

    #
    # JS tests
    #
    - git clone --branch main https://github.com/Cosmian/cloudproof_js.git
    - mkdir -p cloudproof_js/src/pkg/${CI_PROJECT_NAME}
    - cp target/non_regression_vector.json cloudproof_js/tests/data/cover_crypt/rust_non_regression_vector.json
    - cp cloudproof_java/target/test-classes/java_non_regression_vector.json cloudproof_js/tests/data/cover_crypt/
    - cp cloudproof_js/node_modules/non_regression_test_vector.json cloudproof_js/tests/data/cover_crypt/other_js_non_regression_test_vector.json
    - cp cloudproof_flutter/build/non_regression_test_vector.json cloudproof_js/tests/data/cover_crypt/
    - cd cloudproof_js
    - cp -r ../pkg/web/* cloudproof_js/src/pkg/${CI_PROJECT_NAME}/
    - npm install
    - npm test

    #
    # Python tests
    #

    #
    # Flutter tests
    #
    - git clone --branch main https://github.com/Cosmian/cloudproof_flutter.git
    - cp target/x86_64-unknown-linux-gnu/release/libcosmian_${CI_PROJECT_NAME}.so cloudproof_flutter/resources/
    - cp target/non_regression_vector.json cloudproof_flutter/test/resources/cover_crypt/rust_non_regression_vector.json
    - cp cloudproof_java/target/test-classes/java_non_regression_vector.json cloudproof_flutter/test/resources/cover_crypt/
    - cp cloudproof_js/node_modules/non_regression_test_vector.json cloudproof_flutter/test/resources/cover_crypt/
    - cp cloudproof_flutter/build/non_regression_test_vector.json cloudproof_flutter/test/resources/cover_crypt/other_flutter_non_regression_test_vector.json
    - cd cloudproof_flutter
    - flutter pub get
    - flutter test
  allow_failure: true

# TODO
# test_cloudproof_python:
#   stage: test
#   script:

#
# Build without tests
#
build_android:
  extends: .base_compile
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  image: gitlab.cosmian.com:5000/core/ci-rust-android:latest
  script:
    - cargo ndk -t x86 -t x86_64 -t armeabi-v7a -t arm64-v8a -o jniLibs build --release --features ffi --lib
  artifacts:
    paths:
      - jniLibs
    expire_in: 3 mos

build_windows:
  extends: .base_compile
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - cargo build --release --features ffi --target x86_64-pc-windows-gnu
    - cbindgen . -c cbindgen.toml | grep -v \#include | uniq >target/${CI_PROJECT_NAME}.h
    # python build
    - pip install -r python/requirements.txt
    - maturin build --release --features python --target x86_64-pc-windows-gnu --target-dir target_python
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/*.dll
      - target/*.h
      - target/wheels/*win*.whl
    expire_in: 3 mos

#
# benches
#
benchmarks:
  stage: build
  before_script:
    - apt update && apt install -y gnuplot
  script:
    - cargo bench --features full_bench,hybrid
  when: manual

#
# Pack and publish from here
#
pack_all_artifacts:
  stage: pack
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  before_script:
    - apt update && apt install -y zip
  script:
    - zip -r ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}-bin.zip pkg target jniLibs
  artifacts:
    name: cosmian_${CI_PROJECT_NAME}_${CI_COMMIT_TAG}
    paths:
      - ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}-bin.zip
    expire_in: 3 mos

npm_publish:
  image: gitlab.cosmian.com:5000/core/ci-npm:latest
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" > ~/.npmrc
    - wasm-pack build --target web --release --features wasm_bindgen
    - wasm-pack pack
    - wasm-pack publish

cargo_publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - echo "[registry]" > ~/.cargo/credentials
    - echo "token = \"$CRATES_IO\"" >> ~/.cargo/credentials
    - rm -rf /tmp/${CI_PROJECT_NAME}
    - cp -rf . /tmp/${CI_PROJECT_NAME}
    - cd /tmp/${CI_PROJECT_NAME}
    - rm -rf ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}-bin.zip cosmian_${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip jniLibs target
    - cargo publish --token $CRATES_IO
    - rm -rf /tmp/${CI_PROJECT_NAME}

python_publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - pip install twine
    - twine upload -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}" target/wheels/${CI_PROJECT_NAME}-${CI_COMMIT_TAG:1}*.whl
