#+title: Covercrypt
#+subtitle:An efficient ABE-like encryption scheme.
#+options: toc:t
#+latex_compiler: lualatex

#+latex_class: article
#+latex_class_options: [a4paper]

#+latex_header: \usepackage[left=1in, right=1in, top=1in, bottom=1in]{geometry}

#+latex_header: \usepackage{fontspec}
#+latex_header: \usepackage{amsmath, amsfonts, amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \theoremstyle{definition}
#+latex_header: \newtheorem{definition}{Definition}[section]
#+latex_header: \newtheorem*{remark}{Remark}
#+latex_header: \usepackage{pgf-umlsd}
#+latex_header: \usepackage{tikz}
#+latex_header: \usetikzlibrary{shapes,arrows,positioning,calc}
#+latex_header: \usepackage{ebproof}

#+latex_header: \newcommand{\msk}[1]{\mathsf{msk}_{#1}}
#+latex_header: \newcommand{\mpk}[1]{\mathsf{mpk}_{#1}}
#+latex_header: \newcommand{\usk}[2]{\mathsf{usk}_{#1,#2}}
#+latex_header: \newcommand{\enc}[2]{\mathsf{enc}_{#1,#2}}
#+latex_header: \newcommand{\sfusk}{\mathsf{usk}}
#+latex_header: \newcommand{\sfenc}{\mathsf{enc}}
#+latex_header: \newcommand{\iwrt}[1]{\,\Longrightarrow_{#1}\,}
#+latex_header: \newcommand{\attr}[2]{#1_{#2}}
#+latex_header: \newcommand{\powerset}[1]{\mathbb P(#1)}


#+latex_header: \newcommand{\cA}{\mathcal{A}}
#+latex_header: \newcommand{\cB}{\mathcal{B}}
#+latex_header: \newcommand{\cC}{\mathcal{C}}
#+latex_header: \newcommand{\cD}{\mathcal{D}}
#+latex_header: \newcommand{\cH}{\mathcal{H}}
#+latex_header: \newcommand{\cE}{\mathcal{E}}
#+latex_header: \newcommand{\cK}{\mathcal{K}}
#+latex_header: \newcommand{\cO}{\mathcal{O}}
#+latex_header: \newcommand{\cP}{\mathcal{P}}
#+latex_header: \newcommand{\cR}{\mathcal{R}}
#+latex_header: \newcommand{\cS}{\mathcal{S}}
#+latex_header: \newcommand{\cT}{\mathcal{T}}
#+latex_header: \newcommand{\cU}{\mathcal{U}}
#+latex_header: \newcommand{\cV}{\mathcal{V}}
#+latex_header: \newcommand{\bN}{\mathbb{N}}

#+latex_header: \newcommand{\true}{\mathsf{true}}
#+latex_header: \newcommand{\false}{\mathsf{false}}
#+latex_header: \newcommand{\True}{\mathsf{True}}
#+latex_header: \newcommand{\False}{\mathsf{False}}

#+bibliography: references.bib

#+latex: \newpage

* Introduction

In large organizations, pieces of data created by one member are commonly shared
to other members.  However,  some pieces of data are sensitive  and must only be
shared to a specific subset of members. The process of accessing a piece of data
therefore becomes a three-step procedure  requiring members to: (1) authenticate
themselves  to  some  trusted  identity   management  system,  (2)  request  the
authorization to  access this  data from  some trusted  authorization management
system and  (3) request this data  from the storage system  which first verifies
the validity of the identity claim  delivered by the identity management system,
the  validity  of  the  authorization   claim  delivered  by  the  authorization
management system, and the compatibility of those claims.

However, authorization rules may be complex which may lead to operator errors or
bugs in  the authorization and  storage systems. Moreover actors  may misbehave,
which   may  question   our  trust   in   the  authorization   given  by   those
systems. Hopefully, there are ways to raise the need for trust in those systems.
One of them consists in  cryptographically enforcing authorization by encrypting
data under a key owned by the members  of the targeted only.  That way, the only
trusted parties are the targeted members  and the key distribution, which can be
performed in  a centralized Key  Management System (KMS).  But  if authorization
rules are complex, key distribution may  also become complex and hence victim of
the same kind of errors.

Attribute-Based Encryption (ABE) is a tool  that has been extensively studied to
solve exactly this  problem.  However, known ABE schemes are  not very efficient
and not post-quantum-secure which hinders  their adoption. Covercrypt solves the
same  problem  while  relaxing  some  formal constraints  in  order  to  achieve
efficiency in most practical use-cases  while offering both CCA and post-quantum
security, attribute-hiding ciphertexts and key tracing.

Covercrypt assumes  the existence  of a centralized  master authority  holding a
master secret key with  which all other keys are created:  the master public key
is used to encrypt data under its  access policy while user secret keys are also
associated to access policies and can  decrypt all Covercrypt ciphertexts with a
compatible access policy.  Covercrypt follows the KEM-DEM approach in which data
is symmetrically  encrypted under a key  which encapsulation is appended  to the
symmetric ciphertext. More precisely, Covercrypt is a actually Key-Encapsulation
Mechanism with  Access Control  (KEM-AC) --  as defined  in [[kem-ac-definition]] --
that can be  combined with a Data-Encryption Mechanism (DEM)  to obtain a Public
Key Encryption (PKE) scheme.  In the  rest of this document, we therefore prefer
the term Covercrypt /encapsulation/ to the term Covercrypt ciphertext. Moreover,
when necessary,  we use the  terms /user  policy/ and /encapsulation  policy/ to
denote  an  access  policy  associated  to   a  user  secret  and  a  Covercrypt
encapsulation respectively, and  use the term policy the context  makes it clear
whether we refer to a user or encapsulation policy.

* Preliminaries

** Non-Interactive Key Exchange (NIKE)

- Note taken on [2026-07-21 Tue 19:32] \\
  The key-homomorphic definition  from the ETSI document is  insufficient to allow
  for an  easy computation of  $\beta =  (s - \alpha  \cdot s_1) *  s_2^{-1}$. For
  this, we really  need the notion of  field since secret keys  must be invertible
  with respect  to the multiplicative  law.  Then, we  need the notion  that there
  exists a  group generator $\mathfrak  g$ for the public  keys such that  for any
  pair of secret and public keys $(sk, pk)$, $pk = sk \cdot \mathfrak g$.
#+attr_latex: :option [Non-Interactive Key Exchange (NIKE)]
#+begin_definition
A NIKE is  a cryptographic scheme allowing to privately  establish a session key
between  two  parties in  a  non-interactive  fashion  using the  following  two
primitives:
- keygen: :: $\bot \rightarrow \cK_S \times \cK_P$

  This randomized algorithm  returns a new pair of secret  and public keys $(sk,
  pk)$.

- session-key: :: $\cK_P \times \cK_S \rightarrow \cK$

  Upon receiving a  public key $pk \in  \cK_P$ and a secret key  $sk \in \cK_S$,
  returns the associated session  key $K \in \cK$ such that  for any given pairs
  of keys $(sk_1, pk_1)$  and $(sk_2, pk_2)$, $\mathrm{session\text{-}key}(pk_1,
  sk_2) = \mathrm{session\text{-}key}(pk_2, sk_1)$.
Additionally, a NIKE is said to be  /key-homomorphic/ if its public keys form an
Abelian group which scalars are its secret keys.
#+end_definition

#+attr_latex: :option [Elliptic-Curve based NIKE (EC-NIKE)]
#+begin_remark
One instantiation of a key-homomorphic NIKE  is based on an elliptic-curve group
$G$ with prime order  $p$ and group generator $\mathfrak g$  and a hash function
$\cH : G \rightarrow \{0,1\}^\lambda$:

- keygen: :: returns $sk  \overset{\mathdollar}{\longleftarrow} \cU(0, p-1)$ and
  $pk \gets sk \cdot \mathfrak g$.

- session-key: ::  upon receiving $pk = sk \cdot \mathfrak g$ and $sk'$, returns
  $K \gets \cH(sk \cdot sk' \cdot \mathfrak g)$.
#+end_remark

** Key-Encapsulation Mechanism (KEM)

#+attr_latex: :option [Key-Encapsulation Mechanism (KEM)]
#+begin_definition
A KEM  is a cryptographic scheme  associated to the key  spaces $\cK_D$, $\cK_E$
and $\cK$, and encapsulation space $\cE$, that exposes the following primitives:
- keygen: :: $\bot \rightarrow \cK_D \times \cK_E$

  This  randomized   algorithm  returns   a  new   pair  of   decapsulation  and
  encapsulation keys $(dk, ek)$.

- encaps: :: $\cK_P \rightarrow \cK \times \cE$

  This randomized algorithm  takes as input an encapsulation key  $ek \in \cK_E$
  and returns a  new session key $K  \in \cK$ and its  encapsulation $\sfenc \in
  \cE$.

- decaps: :: $\cK_S \times \cE \rightarrow \cK$ or $\bot$

  This  algorithm takes  as input  a  decapsulation key  $dk \in  \cK_D$ and  an
  encapsulation $\sfenc \in  \cE$, and returns the encapsulated  session key $K$
  if  and only  if  the  encapsulation was  created  for  the encapsulation  key
  associated to $dk$.
#+end_definition

** KEM with Access Control (KEM-AC)

A Key-Encapsulation Mechanism with  Access Control (KEM-AC) allows encapsulating
a secret  with respect to an  /encapsulation policy/, such that  user secret key
can open it  if an only if  its associated /user policy/ is  compatible with the
encapsulation policy with respect to some binary relation over the policy space.

#+name: kem-ac-definition
#+attr_latex: :options [Key-Encapsulation Mechanism with Access Control]
#+begin_definition
A KEM-AC  is defined over  a master-secret-key space  $\cK_S$, master-public-key
space $\cK_P$ and a user-secret-key space $\cK_U$, a session-key space $\cK$ and
an encapsulation space $\cE$, and exposes the following operations:
- setup: :: $\mathbb P(\cP_U \times \cP_E) \rightarrow \cK_S \times \cK_P$

  This randomized algorithm takes as input  a binary relation $R$ over policies,
  and returns a master secret key $\msk{R}$ and a master public key $\mpk{R}$.

- keygen: :: $\cK_S \times \cP_U \rightarrow \cK_U$

  This randomized  algorithm takes  as input  a master  secret key  $\msk{R} \in
  \cK_S$ under  a binary relation  $R \subset \cP_U  \times \cP_E$ and  a policy
  $p_u \in \cP_U$, and returns a user secret key $\usk{p_u}{R}$.

- encaps: ::  $\cK_P \times \cP_E \rightarrow \cK \times \cE$

  This randomized algorithm takes as input a master public key $mpk_R \in \cK_P$
  under a  binary relation $R \subset  \cP_U \times \cP_E$ and  an encapsulation
  policy $p_e  \in \cP_E$, and returns  both a session  key $k \in \cK$  and its
  encapsulation $\enc{p_e}{R} \in \cE$.

- decaps: :: $\cK_U \times \cE \rightarrow \cK$ or $\bot$

  This algorithm  takes as input  a user  secret key $\usk{p_u}{R_u}  \in \cK_U$
  associated to  an access policy $p_u  \in \cP_U$ under a  binary relation $R_u
  \subset \cP_U  \times \cP_E$,  and an  encapsulation $\enc{p_e}{R_e}  \in \cE$
  associated to  a policy $p_e \in  \cP_E$ under a binary  relation $R_e \subset
  \cP_U \times \cP_E$.   It returns the encapsulated session key  $k \in \cK$ if
  $(p_u,p_e) \in R_e$, and $\bot$ otherwise.
#+end_definition

* Subset-Cover KEM-AC (SC-KEM-AC)

** KEM-AC specification

Covercrypt is a  subset-cover algorithm: it implements a KEM-AC  with respect to
an  access structure  $S$ defining  a  set of  rights $\cU  = \{r_i\}_i$  called
/universe/, which  policy space is $\mathbb  P(\cU)$ and binary relation  is the
test of  intersection: $R_{\cU} = \{(p_u,  p_e) \in \mathbb P(\cU)^2  : p_u \cap
p_e  \ne \emptyset  \}$.   The  complete reference  implementation  is given  in
Section [[*SC-KEM-AC reference implementation]] (note that the format of the keys is
dictated by the additional requirements listed in the following sections).

** Key and encapsulation life-cycle management

Just like any other keys, Covercrypt keys  can be compromised and lost. There is
therefore the need to renew them.  However,  in order to preserve the ability to
open older encapsulations with renewed keys, it is desirable for the key renewal
to be different from setting up a  new instance. The renewal procedure -- called
/key rotation/ -- is described in the present section.

Recall that  each user secret  key $usk_p$ is associated  to a policy  $p$. Upon
use-secret-key compromise, a key rotation with respect to its entire policy must
be performed.  Due to the particular  structure of Covercrypt keys, this process
implies: (1)  the rotation of all  associated secrets in the  master secret key,
(2) the propagation of this rotation to  the master public key to prevent future
encapsulations from being using compromised secrets, (3) the propagation of this
rotation  to all  user  secret keys  which  policy intersects  the  ones of  the
compromised  key  to  allow  legitimate users  opening  the  new  encapsulations
generated with respect to the new secrets, and (4) optionally the refresh of all
encapsulations which associated policy intersects the one of the compromised key
to prevent  an eventual attacker from  opening them if it  still hasn't accessed
them.      The     entire     key-rotation    process     is     depicted     in
Figure \ref{rotation-flow}, and leverages the following primitives:
- usk-policy: :: $\cK_U \rightarrow \mathbb P(\cU)$

  This function  takes as input a  Covercrypt user secret key  $usk_p \in \cK_U$
  and returns its associated policy $p \subset \cU$.

- rotate: :: $\cK_S \times \mathbb P(\cU) \rightarrow \cK_S \times \cK_P$

  This randomized  algorithm takes as input  a master secret key  $\msk{\cU} \in
  \cK_S$ and an access policy $p^* \subset \cU$, refreshes every secrets in this
  given master secret key that are associated  to a right in this policy (/i.e./
  each secret associated to a right in  $s \cap p^*$), and returns the refreshed
  master secret key along with its associated master public key.

- usk-refresh: :: $\cK_S \times \cK_U \rightarrow \cK_U$ or $\bot$

  This algorithm takes as  input a master secret key $msk \in  \cK_S$ and a user
  secret key $usk_p  \in \cK_U$ associated to  a policy $p \subset  \cU$. If the
  integrity of the  given user secret key  can be verified by  the master secret
  key, it returns a  new user secret key $usk_p'$ associated  to the same access
  policy containing all secrets that are contained in the given user secret key,
  plus new secrets for each rights in  $p$ for which newer secrets exists in the
  master secret key.   If the integrity of  the given user secret  key cannot be
  verified, $\bot$ is returned.

- enc-refresh: ::   $\cK_S \times \cK_P \times \cE \rightarrow \cE$ or $\bot$

  This randomized algorithm takes as input  a master secret key $msk \in \cK_S$,
  a  master public  key $mpk  \in \cK_S$  and an  encapsulation $enc_p  \in \cE$
  associated to a policy $p \subset \cU$.  If the integrity of the master public
  key  can be  verified, that  its revision  number matches  that of  the master
  secret  key,  and  that the  encapsulation  can  be  open,  it returns  a  new
  encapsulation $enc_p'$ associated to the  same access policy. Otherwise $\bot$
  is returned.

#+begin_export latex
\tikzset{
  block/.style = {draw, fill=white, rectangle, minimum height=3em, minimum width=3em},
  tmp/.style  = {coordinate},
  sum/.style= {draw, fill=white, circle, node distance=2cm},
  input/.style = {coordinate},
  output/.style= {coordinate},
  pinstyle/.style = {pin edge={to-,thin,black}
  }
}

\begin{figure}
  \center
  \begin{tikzpicture}[auto, node distance=2cm,>=latex']
    \node [input] (usk) {};
    \node [block, right of=usk, node distance = 2.5cm] (pol) {usk-policy};
    \node [block, right of=pol, node distance = 2.5cm] (rot) {rotate};
    \node [input, below of=pol, node distance = 2.5cm] (enc) {};
    \node [block, below of=rot, node distance = 2.5cm, dashed] (erf) {enc-refresh};
    \node [input, above of=rot] (msk){};
    \node [output, below of=rot] (mout){};
    \node [output, below of=erf] (eout){};
    \node [block, right of=rot, node distance = 2.5cm] (urf) {usk-refresh};
    \node [input, above of=urf] (uski_old){};
    \node [output, below of=urf] (uski_new){};
    \draw [->] (rot) -- node{$msk'$} (urf);
    \draw [->] (rot) -- node{$\left(msk', mpk'\right)$} (mout);
    \draw [->] (erf) -- node{$enc_{p_j}$ or $\bot$} (eout);
    \draw [->] (uski_old) -- node{$usk_{p_i}^*$} (urf);
    \draw [->] (usk) -- node{$usk_{p^*}^*$} (pol);
    \draw [->] (enc) -- node{$enc_{p_j}^*$} (erf);
    \draw [->] (urf) -- node{$usk_{p_i}$ or $\bot$} (uski_new);
    \draw [->] (pol) -- node{$p^*$} (rot);
    \draw [->] (msk) -- node{$msk$} (rot);
  \end{tikzpicture}
  \caption{\label{rotation-flow}User-secret-key rotation flow, where untrusted objects are marked with an asterix.}
\end{figure}
#+end_export

#+begin_remark
Checking the  integrity of the user  secret key (resp.  encapsulation  key) upon
refresh is required  to prevent right escalation  (resp.  impersonification) via
modification of  this key, while  encapsulation policies cannot be  modified via
modification  of  the  encapsulation  due  to the  CCA  security  guaranteed  by
Covercrypt encapsulations.
#+end_remark

Additionally, to prevent impersonification attacks upon encapsulation, users can
always verify the integrity of the master public key using user secret keys, and
since this is necessary to prevent right-escalation attacks upon user-secret-key
refresh, we also provide a way to verify the integrity of user secret keys using
the master secret key:
- mpk-verify: :: $\cK_U \times \cK_P \rightarrow \cB$

  Returns whether the  integrity of the given master public  key $mpk \in \cK_P$
  can be verified using the given user secret key $usk_p \in \cK_U$.

- usk-verify: :: $\cK_S \times \cK_P \rightarrow \cB$

  Returns whether the  integrity of the given user secret  key $usk_p \in \cK_U$
  can be verified using the given master secret key $msk \in \cK_S$.

Finally, a Covercrypt instantiation is  associated to a sequence of /revisions/:
the setup initializes  an instance with /revision number/ 0,  and each execution
of the key rotation procedure increments this  number by one and returns the new
value of the master secret key with the new revision number.  Covercrypt objects
can only create objects with the same revision number which can be extracted via
one of the following functions:
- msk-revision: :: $\cK_S \rightarrow \bN$

  Retrieves the  revision number from  the given  master secret key  $\msk{} \in
  \cK_S$.

- mpk-revision: :: $\cK_P \rightarrow \bN$

  Retrieves the  revision number from  the given  master public key  $\mpk{} \in
  \cK_P$.

- usk-revision: :: $\cK_U \rightarrow \bN$

  Retrieves the  revision number from  the given  master public key  $\sfusk \in
  \cK_U$.

- enc-revision: :: $\cE \rightarrow \bN$

  Retrieves the revision number from the encapsulation $\sfenc \in \cE$.

#+begin_remark
Downgrade attacks upon  encapsulation can be avoided by  verifying the integrity
of the master public key used, and that its revision number is no less than that
of the user secret key.
#+end_remark

** TODO Hybridization à la carte

To accommodate different regulations and  right sensitivities, it is possible to
describe for each  right the kind of  encapsulation to generate, among  a set of
predefined encapsulation kinds.

** Live access-structure modifications

Real-life access  structure may evolve  with time.  Covercrypt reflects  this by
exposing primitives  allowing to  modify the policy  universe without  having to
perform a new  setup. In particular, additive modifications of  the universe are
/backward-compatible/:  old user  secret  keys and  encapsulations  need not  be
modified in order to open new compatible  encapsulations, or to be opened by new
compatible user secret keys. In other words, additive universe modifications can
be seen as the use of a right  that was present in the universe but unused until
then.
- add-rights: :: $\cK_S \times \mathbb P(\cR) \rightarrow \cK_S \times \cK_P$

  This randomized algorithm  takes as input a master secret  key $msk \in \cK_S$
  under a universe  $\cU$ and a set  of new rights $\{r_i\}_i  \subset \cR$, and
  returns new  master secret and  public keys under  a universe $\cU'  \gets \cU
  \cup \{r_i\}_i$.

- del-rights: :: $\cK_S \times \mathbb P(\cR) \rightarrow \cK_S \times \cK_P$

  This randomized algorithm  takes as input a master secret  key $msk \in \cK_S$
  under a universe  $\cU$ and a set  of new rights $\{r_i\}_i  \subset \cR$, and
  returns new  master secret and  public keys with incremented  revision numbers
  under a universe $\cU' \gets \cU \setminus \{r_i\}_i$.

#+begin_remark
Additive universe modifications do not  generate new revisions while destructive
universe  modifications  generate  new  revisions since  downgrade  attacks  can
leverage  master public  keys  prior to  the  removal of  some  rights from  the
universe to trick users create encapsulations for compromised secrets.
#+end_remark

** SC-KEM-AC reference implementation

In this section, we give a reference implementation for the Covercrypt SC-KEM-AC
algorithm.   This implementation  is optimized  for  simplicity and  may not  be
optimized for speed. It presupposes the  existence of a key-homomorphic NIKE and
KEM schemes as described in the Section [[*Preliminaries]].

*** Key format

*** SC-KEM-AC primitives

This implementation presuppose the existence of hash functions $\mathtt{G, H, J,
U, T}$ which signatures are as follows:
- $G : \{0,1\}^* \rightarrow \cK_S^\mathrm{nike}$
- $T : (\cE^\mathrm{kem})^* \rightarrow \cT_T$
- $U : (\{0,1\}^*)^* \rightarrow \cT_U$
- $H : \cK^\mathrm{nike} \times \cK^{kem} \times \cK_P^\mathrm{nike} \times
  \cK_P^\mathrm{nike} \times \cT_T \rightarrow \{0,1\}^*$
- $J : \{0,1\}^* \times \cK_P^\mathrm{nike} \times \cK_P^\mathrm{nike} \times
  \cT_U \rightarrow \{0,1\}^* \times \{0,1\}^*$
Or, alternatively:
  #+begin_src ocaml
    module type G = sig
      val hash : bytes -> Nike.sk
    end

    module type T = sig
      type t

      val hash : Kem.enc list -> t
    end

    module type U = sig
      type t

      val hash : bytes list -> t:T.t -> t
    end

    module type H = sig
      val hash : Nike.key -> Kem.key -> c1:Nike.pk -> c2:Nike.pk -> T.t -> bytes
    end

    module type J = sig
      type key
      type tag

      val hash : secret:bytes -> c1:Nike.pk -> c2:Nike.pk -> U.t -> key * tag
    end
  #+end_src
Notice that the output  of ~T~ and ~U~ are abstract and  thus different from any
other type, and that the ~key~ output of  ~J~ is the type of the key returned by
the  ~encaps~  and  ~decaps~  primitives.   With this  in  mind,  the  reference
implementation of the primitives of Covercrypt SC-KEM-AC is as follows:

- setup: :: $\cU \rightarrow \cK_S \times \cK_P$

  This  randomized algorithm  takes as  input a  universe $\cU$,  and returns  a
  master secret  key $\msk{R_\cU}$  and a master  public key  $\mpk{R_\cU}$.

  #+include: "covercrypt.ml" src ocaml :lines "332-359"

  Note the  companion procedure ~get_mpk msk~  that can be used  to the generate
  master public keys from the master secret key after the setup.

- keygen: :: $\cK_S \times \cP_U \rightarrow \cK_U$

  #+include: "covercrypt.ml" src ocaml :lines "360-376"

- encaps: ::  $\cK_P \times \cP_E \rightarrow \cK \times \cE$

  #+include: "covercrypt.ml" src ocaml :lines "377-409"

- decaps: :: $\cK_U \times \cE \rightarrow \cK$ or $\bot$

  #+include: "covercrypt.ml" src ocaml :lines "429-444"

  Where ~try_decaps~ attempts opening a right encapsulation as follows:

  #+include: "covercrypt.ml" src ocaml :lines "415-428"


*** Key-rotation primitives

- usk-policy: :: $\cK_U \rightarrow \mathbb P(\cU)$

  Extracting the policy out of a user secret key simply resorts to retrieving
  the rights for which it holds secrets:

  #+include: "covercrypt.ml" src ocaml :lines "490-492"

- rotate: :: $\cK_S \times \mathbb P(\cU) \rightarrow \cK_S \times \cK_P$

  #+include: "covercrypt.ml" src ocaml :lines "493-501"

- usk-refresh: :: $\cK_S \times \cK_U \rightarrow \cK_U$ or $\bot$

  #+include: "covercrypt.ml" src ocaml :lines "502-529"

- enc-refresh: :: $\cK_S \times \cK_P \times \cE \rightarrow (\cK \times \cE)$
  or $\bot$

  #+include: "covercrypt.ml" src ocaml :lines "475-484"

  Where ~enc_policy~ allows retrieving the policy of an encapsulation along with
  the encapsulated key:

  #+include: "covercrypt.ml" src ocaml :lines "453-474"

*** Live-universe-modification primitive

* Boolean KEM-AC

In order to  make expressing policies more ergonomic, we  introduce KEM-AC which
policy space  is a  set of  logical propositions  that is  closed under  the two
logical  operators /and/  ($\land$) and  /or/ ($\lor$).   Then, we  show how  to
implement  this  boolean KEM-AC  on  top  of  the  set-based KEM-AC  defined  in
Section [[*Subset-Cover  KEM-AC  (SC-KEM-AC)]]  via compiling  boolean  policies  to
set-based policies.

** Syntax and semantics

The policy language has a very simple syntax which specification is given below,
and which semantics is defined thereafter.
#+name: policy-language-syntax
#+caption: Syntax of the policy language.
#+begin_example
  <policy>    ::= <attribute> | <policy> <operator> <policy>
  <operator>  ::= "&&" | "||"
  <attribute> ::= "*" | <dimension>::<name>
  <dimension> ::= <name>
  <name>      ::= <word> \ { "&&" | "||" | <word>::<word> }
  <word>      ::= char+
#+end_example

#+attr_latex: :options [Universe]
#+begin_definition
In the boolean KEM-AC setting, the universe  $\Omega$ is a set of atomic logical
propositions called /attributes/.
#+end_definition

#+attr_latex: :options [Policies]
#+begin_definition
The  space of  policies  $\cP_\Omega$  associated to  a  universe of  attributes
$\Omega$ is the closure of $\Omega$ with respect to both logical operators /and/
($\land$)  and /or/  ($\lor$), noted  $\cP_\Omega =  \left< \Omega,  \land, \lor
\right>$. In other words,  a policy is a function of sets  of true attributes in
$\Omega$   to   the   set   of  boolean   values   $\cB$:   $\cP_\Omega   \simeq
\powerset{\Omega}^\cB$. Given  a set of  true attributes $X \subset  \Omega$, we
therefore use $p(X)$  to denote the value  taken by a policy  $p \in \cP_\Omega$
when exactly those attributes are set to true.
#+end_definition

#+begin_remark
$\cP_\Omega$  has two  special policies,  noted $\True$  and $\False$,  that are
respectively always true and false.
#+end_remark

# #+attr_latex: :options [Implication in $\cU$]
# #+begin_definition
# Given two  logical propositions  $(p, p')  \in \cP_\Omega^2$  and a  universe of
# expressible attributes $\cU \subset \Omega$, $p$ is said to imply $p'$ in $\cU$,
# noted  $p \iwrt{\cU}  p'$, if  and only  if  $p$ implies  $p'$ when  the set  of
# attributes that are possibly true is restricted to $\cU$: \[ \forall (p, p') \in
# \cP_\Omega^2, (p \iwrt{\cU} p') \iff \forall  X \subset \cU, p(X) \implies p'(X)
# \]
# #+end_definition

In order to structure the set of expressible policies, the values attributes can
take  can be  constrained  by the  definition of  an  access structure  grouping
logically-related  attributes  together  by either  anarchical  or  hierarchical
dimensions.

#+attr_latex: :options [Dimension]
#+begin_definition
A  dimension $D$  of a  universe of  attributes $\Omega$  is a  constraint on  a
non-empty set of attributes from $\Omega$ requiring that at least one of them be
true:
#+begin_export latex
\begin{equation}
  \tag{dimension}
  \bigvee_{a \in D} a = \True
\end{equation}
#+end_export
The set  of dimensions of $\Omega$, noted $\cD_\Omega$,  is therefore the
set of its non-empty parts:  $\cD_\Omega = \powerset{\Omega}^*$.
#+end_definition

#+attr_latex: :options [Hierarchy]
#+begin_definition
A dimension $D \in \cD_\Omega$ defined by  an access structure $S$ is said to be
a hierarchy if it is associated  a bijective function $\iota \in D^{[1,|D|]}$ in
$S$.  In that  case, it additionally requires that the  logical implication be a
strict total order over $D$:
#+begin_export latex
\begin{equation}
  \tag{hierarchy}
  \forall (a, a') \in D^2, a  \implies a' \iff \iota(a) > \iota(a')
\end{equation}
#+end_export
#+end_definition

#+attr_latex: :options [Anarchy]
#+begin_definition
Otherwise,  a  dimension  $D \in  \cD_\Omega$  is  said  to  be an  anarchy  and
additionally requires its attributes to be mutually exclusive:
#+begin_export latex
\begin{equation}
  \tag{anarchy}
  \forall (a, a') \in D^2,
  \left( a = a' \right) \lor \left( a \implies \neg a' \right)
\end{equation}
#+end_export
#+end_definition

Not all combinations of dimensions can be defined by a given access structure.

#+attr_latex: :options [Access Structure]
#+begin_definition
In the boolean KEM-AC setting, an access structure is a set of mutually disjoint
dimensions: \[ \cS = \{S \in \mathbb P(\cD) \mid \forall (D_i, D_j) \in S^2, D_i
\cap D_j = \emptyset \}\]
#+end_definition

#+attr_latex: :options [Set of Expressible Postulates]
#+begin_definition
The set of expressible postulates $\cU_S \subset \powerset{\Omega}$ described by
an access  structure $S$ is  the set  of parts of  $\Omega$ that are  valid with
respect to each dimension in $S$.
# :  \[\cU = \left\{X \in  \powerset{\Omega} \mid
# (D,  \iota) \in  S, a  \in X  \cap  D \implies  \forall a'  \in D  : \iota(a)  >
# \iota(a'), a' \in X \right\}\]
#+end_definition

#+attr_latex: :options [Valid Policy]
#+begin_definition
A policy $p$ is said to be valid  with respect to an access structure $S$, noted
$p \in \cV_S$ if and only if  there exists a postulate in $\cU_S$ that validates
$p$: \[ p \in \cV_S \iff \exists X \in \cU_S : p(X) = \true \]
#+end_definition

** KEM-AC

In the boolean KEM-AC setting, a  user secret key $\usk{p_u}{S}$ associated to a
policy $p_u \in \cP_\cU$ can open an encapsulation $\enc{p_e}{S'}$ associated to
a policy $p_e \in \cP_\Omega$ if and  only if the conjunction of $p_u$ and $p_e$
is valid with respect to both $S$ and  $S'$: \[ (p_u, p_e) \in R \iff (p_u \land
p_e) \in (\cV_S \cap \cV_{S'})\]

#+begin_remark
It is  important to distinguish the  access structure in which  an encapsulation
was  created from  the one  in which  a user  secret key  was created  since the
universe of expressible postulates can be modified  in such a way that an access
policy that is valid w.r.t.  a first access structure $S$ becomes invalid w.r.t.
the new access structure $S'$.
#+end_remark

*** Examples

**** Without access structure modification

Let $S = \{A, (H, \iota)\}$, where $A = \{ \attr{a}{1}, \attr{a}{2}, \attr{a}{3}
\}$ is an  anarchical dimension, and $H  = \{ \attr{1}{h}, \attr{2}{h}  \}$ is a
hierarchical dimension with $\iota(\attr{2}{h}) > \iota(\attr{1}{h})$.

- Let  $p_u  = \attr{a}{1}  \land  \attr{2}{h}$  and  $p_e =  \attr{a}{1}  \land
  \attr{2}{h}$. In this  case, a user secret key $\usk{p_u}{\cU}$  /can/ open an
  encapsulation  $\enc{p_e}{\cU}$  since  $p_u  \land p_e  =  \attr{a}{1}  \land
  \attr{2}{h} \ne \False$.

- Let $p_u =  \attr{a}{1} = \attr{a}{1} \land \attr{1}{h}$  using the definition
  of a hierarchical dimension. Let $p_e = \attr{2}{h} = \attr{2}{h} \land \left(
  \lor_{i=1}^{3}   \attr{a}{i}  \right)   =   (\attr{2}{h}  \land   \attr{a}{1})
  \lor_{i=2}^{3}  \left(  \attr{2}{h}  \land   \attr{a}{i}  \right)$  using  the
  definition of an anarchical dimension.

  In  this   case,  a  user   secret  key  $\usk{p_u}{\cU}$  /cannot/   open  an
  encapsulation   $\enc{p_e}{\cU}$    since   $\neg    (\attr{1}{h}   \iwrt{\cU}
  \attr{2}{h})$ by definition of a hierarchical dimension.


**** With expressible universe modification

***** Additive transformation

Let $\cU' = \cU  \cup D_3$, where $D_3 = \{  \attr{3}{1}, \attr{3}{2} \} \subset
\cA_\Omega$ is an anarchical dimension.
- Let  $p_u  = \attr{1}{1}  \land  \attr{2}{2}$  and  $p_e =  \attr{1}{1}  \land
  \attr{2}{2}  \land  \attr{3}{2}$.  Then  a  user  secret key  $\usk{p_u}{\cU}$
  /cannot/ decrypt  $\enc{p_e}{\cU'}$ since  $p_e =_{\cU} \False$  and $\neg(p_u
  \iwrt{\cU} \False)$.

  $p_u   =_{\cU'}  \attr{1}{1}   \land  \attr{2}{2}   \land  (\attr{3}{1}   \lor
  \attr{3}{2})$

- Let  $p_u  = \attr{1}{1}  \land  \attr{2}{2}$  and  $p_e =  \attr{1}{1}  \land
  \attr{2}{2}  \land  \attr{3}{2}$.  Then  a user  secret  key  $\usk{p_u}{\cU}$
  /cannot/ decrypt $\enc{p_e}{\cU'}$ since


***** Destructive transformation

** TODO Live universe modifications

Evolving  the access  structure  underlying  a given  revision  of a  Covercrypt
instance can be done through one of those functions:
- add-hierarchy: :: $\cK_S \times \mathbb P(\cR) \rightarrow
  \cK_S \times \cK_P$ or $\bot$
- del-hierarchy: :: $\cK_S \times \mathbb P(\cR) \rightarrow
  \cK_S \times \cK_P$ or $\bot$

  This randomized algorithm  takes as input a master secret  key $msk \in \cK_S$
  with an access structure $S$ and a  set of attributes $D \subset \cR$. If this
  new hierarchy is valid with respect to $S$, it returns a new master secret key
  and a new master public key which structure contains (resp.  does not contain)
  $H$. Otherwise $\bot$ is returned.

- add-anarchy: :: $\cK_S \times \cA \rightarrow \cK_S
  \times \cK_P$ or $\bot$
- del-anarchy: :: $\cK_S \times \cA \rightarrow \cK_S
  \times \cK_P$ or $\bot$

  This randomized algorithm  takes as input a master secret  key $msk \in \cK_S$
  with an access structure $S$ and an  anarchical dimension $A \in \cA$. If this
  new anarchy is valid  with respect to $S$, it returns a  new master secret key
  and a new master public key which structure contains (resp.  does not contain)
  $A$. Otherwise $\bot$ is returned.

- add-attribute: :: $\cK_S \times \cA \times \cU
  \rightarrow \cK_S \times \cK_P$ or $\bot$
- del-attribute: ::  $\cK_S \times \cA \times \cU
  \rightarrow \cK_S \times \cK_P$ or $\bot$

  This randomized algorithm  takes as input a master secret  key $msk \in \cK_S$
  with  an access  structure $S$,  an anarchical  dimension $D  \in \cA$  and an
  attribute $p \in \cU$. If this dimension is  a member of $S$, it returns a new
  master secret  key and  a new master  public key with  an access  structure in
  which this dimension contains (resp. does not contain) this attribute.

- add-hierarchical-attribute: :: $\cK_S \times \cH \times \cU \rightarrow \cK_S
  \times \cK_P$ or $\bot$
- del-hierarchical-attribute: :: $\cK_S \times \cH \times \cU \rightarrow \cK_S
  \times \cK_P$ or $\bot$

  This randomized algorithm  takes as input a master secret  key $msk \in \cK_S$
  with an  access structure  $S$, a  hierarchical dimension $D  \in \cH$  and an
  attribute $p \in \cU$. If this dimension is  a member of $S$, it returns a new
  master secret  key and  a new master  public key with  an access  structure in
  which this dimension contains (resp. does not contain) this attribute.

** TODO Hybridization à la carte

* TODO Optional key tracing
* TODO Cooperating Covercrypt authorities

Covercrypt  suppose  the  existence  of   an  central  authority  in  charge  of
maintaining the master secret key, and  generating the master public key and all
user secret keys. However, in some use  cases, it is desirable to distribute the
power over  multiple authorities: users managed  by a given authority  should be
able to create encapsulations for attributes defined by a different authority.

Doing so requires  (1) generating fragments of a master  public key by selecting
the subset of the rights from the original key that is targeted for sharing, and
(2) combining master public key fragments together to create a new master public
key:
- ~select:~ :: ~mpk -> policy -> mpk~
- ~combine:~ :: ~mpk -> mpk -> mpk~
Doing so requires a broader acception of  what a master public key is since such
key may not contain all rights hold by its associated master secret key, and may
not even be associated to a single master secret key anymore.

#+latex: \newpage
#+latex: \appendix

* Reference implementation

#+include: "covercrypt.ml" src ocaml

* TODO COMMENT Implementation considerations
** Key and encapsulation formats

Covercrypt is parameterized by:
- a signature scheme that could be described by the following signature:
  #+begin_src ocaml :session :results none
    module type Signature = sig
      type sk
      type vk
      type signature

      val sign : sk -> msg:string -> signature
      val verf : vk -> msg:string -> signature -> bool
    end
  #+end_src

- a mac scheme that could be described by the following signature:
  #+begin_src ocaml :session :results none
    module type MAC = sig
      type key
      type tag

      val mac : key -> msg:string -> tag
    end
  #+end_src

- a key-homomorphic Non-Interactive Key-Exchange (NIKE) scheme that could be
  described as:
  #+begin_src ocaml :session :results none
    module type Group = sig
      type t

      val id : t
      val op : t -> t -> t
      val inv : t -> t
    end

    module type AbelianGroup = sig
      include Group

      val zero : t
      val ( + ) : t -> t -> t
      val ( - ) : t -> t -> t
    end

    module type Ring = sig
      include AbelianGroup

      val one : t
      val ( * ) : t -> t -> t
      val ( / ) : t -> t -> t option
    end

    module type KH_NIKE = sig
      module Sk : Ring
      module Pk : Group

      type key
      type rng

      val op : Pk.t -> Sk.t -> Pk.t
      val keygen : rng -> Sk.t * Pk.t
      val session : Pk.t -> Sk.t -> key
    end
  #+end_src
  Such that: ~session (op pk sk) sk' = session pk Ring.(sk * sk')~.
- a KEM that could be described by the following signature:
  #+begin_src ocaml :session :results none
    module type KEM = sig
      type dk
      type ek
      type ss
      type enc
      type rng

      val keygen : rng -> dk * ek
      val encaps : rng -> ek -> ss * enc
      val decaps : dk -> enc -> ss
    end
  #+end_src

*** Master secret key

The master secret key is composed of:
1. a revision number $v$;
2. a signing key $sk$ used to sign the master public key;
3. a mac key $k$ used to verify the integrity of user secret keys;
4. a tracing secret key $tsk$;
5. a mapping $rsk$ from rights to histories of secrets.
#+begin_src ocaml :results none :session
  module Covercrypt_msk
      (S : Signature)
      (M : MAC)
      (Nike : KH_NIKE)
      (Kem : KEM)
      (Right : sig type t end)
  = struct
    type msk = {
      v : int;
      k : M.key;
      sk : S.sk;
      tsk : tsk;
      rsk : rsk;
    }
    and tsk = Nike.Sk.t list
    and rsk = (Right.t, secret list) Hashtbl.t
    and secret =
      | N of Nike.Sk.t
      | K of Kem.dk
      | H of Nike.Sk.t * Kem.dk
  end
#+end_src
With the additional constraints that there exist a tracing threshold $t \in
\mathbb N^*$ such that $|tsk| = t + 2$.

*** Master public key

The master public key is composed of:
1. a revision number $v$;
2. a tracing public key $tpk$;
3. a mapping $rpk$ from the right to a public element;
4. a signature $\sigma$ of its other components under the signing key of the
   master secret key;
#+begin_src ocaml :results none :session
  module Covercrypt_mpk
      (S : Signature)
      (Nike : KH_NIKE)
      (Kem : KEM)
      (Right : sig type t end)
  = struct
    type mpk = {
      v : int;
      tpk : tpk;
      rpk : rpk;
      sgn : S.signature;
    }
    and tpk = Nike.Pk.t list
    and rpk = (Right.t, elt list) Hashtbl.t
    and elt =
      | N of Nike.Pk.t
      | K of Kem.ek
      | H of Nike.Pk.t * Kem.ek
  end
#+end_src
With the additional constraints that there exist a tracing threshold $t \in
\mathbb N^*$ such that $|tpk| = t + 2$.

*** User secret key
A user secret key is composed of:
1. a revision number $v$;
2. a verification key $vk$ to verify the master public key;
3. a tracing user key $tuk$;
4. a mapping $ruk$ of rights onto histories of secrets;
5. a MAC tag of its other components.
#+begin_src ocaml :results none :session
  module Covercrypt_usk
      (S : Signature)
      (M : MAC)
      (Nike : KH_NIKE)
      (Kem : KEM)
      (Right : sig type t end)
  = struct
    type usk = {
      v : int;
      vk : S.vk;
      tuk : tuk;
      ruk : ruk;
      tag : M.tag
    }
    and tuk = Nike.Sk.t list
    and ruk = (Right.t, secret list) Hashtbl.t
    and secret =
      | N of Nike.Sk.t
      | K of Kem.dk
      | H of Nike.Sk.t * Kem.dk
  end
#+end_src
With the additional constraints that there exist a tracing threshold $t \in
\mathbb N^*$ such that $|tuk| = t + 1$.

*** Encapsulation

An encapsulation is composed of:
1. a revision number $v$;
2. a verification tag;
3. a tracing encapsulation $tenc$;
4. an attribute-hiding access-control encapsulation $renc$;
#+begin_src ocaml :results none :session
  module Sized_string = struct
    module type S = sig
      type t
      val size : int
      val to_string : t -> string
      val of_string : string -> t option
    end

    module Make (P : sig val size : int end) : S = struct
      type t = string
      let size = P.size
      let to_string s = s
      let of_string s =
        if String.length s = size
        then Some s else None
    end
  end

  module Covercrypt_enc
      (Nike : KH_NIKE)
      (Kem : KEM)
  = struct
    module VTag = Sized_string.Make (struct let size = 16 end)
    module NEnc = Sized_string.Make (struct let size = 32 end)
    type enc = {
      v : int;
      tag : VTag.t;
      tenc : Nike.Pk.t list;
      renc : renc;
    }
    and renc =
      | N of NEnc.t list
      | K of Kem.enc list
      | H of NEnc.t * Kem.enc
  end
#+end_src
With the additional constraints that there exist a tracing threshold $t \in
\mathbb N^*$ such that $|tenc| = t + 1$.

** COMMENT KEM-AC

A KEM-AC  can be defined by  the following signature:
#+name: kem-ac-signature
#+begin_src ocaml
  module type KEMAC = sig
    type rng
    type msk
    type mpk
    type usk
    type enc
    type secret
    type policy
    type structure

    val setup : rng -> structure -> msk * mpk
    val keygen : rng -> msk -> policy -> usk option
    val encaps : rng -> mpk -> policy -> (secret * enc) option
    val decaps : usk -> enc -> secret option
  end
#+end_src

* TODO COMMENT Wish-list
