---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cover_crypt:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@main
    with:
      project-name: cover_crypt
      toolchain: stable
      kms-version: 4.0.1
      regression-filename: non_regression_vector.json
      branch-java: main
      branch-js: main
      branch-flutter: main
      branch-python: main
      bench-features: full_bench,hybrid
    secrets: inherit
