---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cover_crypt:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@main
    with:
      project-name: cover_crypt
      toolchain: stable
      kms-version: 4.1.0
      regression-filename: non_regression_vector.json
      branch-java: feature/use_cover_crypt_v9
      branch-js: feature/use_cover_crypt_v9.0
      branch-flutter: feature/add_github_ci
      branch-python: feature/kms
      bench-features: full_bench,hybridized_bench
    secrets: inherit
