---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cover_crypt:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@main
    with:
      project-name: cover_crypt
      toolchain: stable
      kms-version: feature-use-cover-crypt-v9
      regression-filename: non_regression_vector.json
      branch-java: main
      branch-js: feature/use_cover_crypt_v9.0
      branch-flutter: main
      branch-python: main
      bench-features: full_bench,hybridized_bench
    secrets: inherit
