---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cover_crypt:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@main
    with:
      project-name: cover_crypt
      toolchain: stable
      kms-version: 4.2.0
      regression-filename: non_regression_vector.json
      branch-java: develop
      branch-js: develop
      branch-flutter: develop
      branch-python: develop
      bench-features: full_bench,hybridized_bench
    secrets: inherit
